PROJ=kbd

OBJS=kbdroute.obj kbdcharin.obj kbdpeek.obj kbdflushbuffer.obj kbdgetstatus.obj kbdsetstatus.obj &
kbdstringin.obj kbdopen.obj kbdclose.obj kbdgetfocus.obj kbdfreefocus.obj kbdgetcp.obj &
kbdsetcp.obj kbdxlate.obj kbdsetcustxt.obj kbdgethwid.obj

EXPORT=KBDCHARIN.1 RESIDENT
IMPORT=bkscalls.lib

!include <..\dll.mk>

