;/*!
;   @file
;
;   @brief BvsGetMode DOS wrapper
;
;   (c) osFree Project 2021, <http://www.osFree.org>
;   for licence see licence.txt in root directory, or project website
;
;   This is Family API implementation for DOS, used with BIND tools
;   to link required API
;
;   @author Yuri Prokushev (yuri.prokushev@gmail.com)
;
;*0  NO_ERROR
;*436 ERROR_VIO_INVALID_HANDLE
;*438 ERROR_VIO_INVALID_LENGTH
;*465 ERROR_VIO_DETACHED
;*494 ERROR_VIO_EXTENDED_SG
;
; @todo add check for structure length
;
;*/

.8086
		; Helpers
		INCLUDE	HELPERS.INC
		INCLUDE DOS.INC
		INCLUDE BSEERR.INC

VIOMODEINFO STRUC

VIOMI_CB             DW ? ;LENGTH OF THE ENTIRE DATA STRUCTURE
VIOMI_FBTYPE         DB ? ;BIT MASK OF MODE BEING SET
VIOMI_COLOR          DB ? ;NUMBER OF COLORS (POWER OF 2)
VIOMI_COL            DW ? ;NUMBER OF TEXT COLUMNS
VIOMI_ROW            DW ? ;NUMBER OF TEXT ROWS
VIOMI_HRES           DW ? ;HORIZONTAL RESOLUTION
VIOMI_VRES           DW ? ;VERTICAL RESOLUTION
VIOMI_FMT_ID         DB ? ;ATTRIBUTE FORMAT
VIOMI_ATTRIB         DB ? ;NUMBER OF ATTRIBUTES
VIOMI_BUF_ADDR       DD ? ;
VIOMI_BUF_LENGTH     DD ? ;
VIOMI_FULL_LENGTH    DD ? ;
VIOMI_PARTIAL_LENGTH DD ? ;
VIOMI_EXT_DATA_ADDR  DD ? ;
VIOMODEINFO ENDS

_TEXT		SEGMENT BYTE PUBLIC 'CODE' USE16

		@BVSPROLOG	BVSGETMODE
VIOHANDLE	DW	?		;Video handle
MODEINFO	DD	?		;
		@BVSSTART	BVSGETMODE

		EXTERN	VIOCHECKHANDLE: PROC
		MOV     BX,[DS:BP].ARGS.VIOHANDLE	; GET HANDLE
		CALL	VIOCHECKHANDLE
		JNZ	EXIT

		LDS     SI,[DS:BP].ARGS.MODEINFO
		MOV	AH, 0FH
		INT	10H
		MOV	AL, AH
		XOR	AH, AH
		MOV     [DS:SI].VIOMODEINFO.VIOMI_COL,AX      ;COLUMNS
		MOV	AX, 25
		MOV     [DS:SI].VIOMODEINFO.VIOMI_ROW,AX      ;ROWS 
		MOV     AL,1
		MOV     [DS:SI].VIOMODEINFO.VIOMI_FBTYPE,AL      ;TYPE: 1=TEXT MODE/3=GRAPH MODE
		MOV     AL,4
		MOV     [DS:SI].VIOMODEINFO.VIOMI_COLOR,AL      ;COLOR: 16 COLORS

		XOR     AX,AX
EXIT:
		@BVSEPILOG	BVSGETMODE
_TEXT		ENDS
		END

