on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
    steps:
      - name: Build for Windows
        run: fapi
        shell: cmd
