on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
    steps:
      - name: Repo clone
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build for Windows
        run: fapi.cmd
        shell: cmd
