on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest

  steps:
    - uses: actions/checkout@v2

    - name: Build for Windows
    if: matrix.os == 'windows-latest'
    run: fapi.cmd
